import type { Metadata } from "next";
import { Dosis } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/theme-provider";
import Header from "@/components/Header";

const dosis = Dosis({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={dosis.className}>
                {" "}
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <main
                        className="flex min-h-screen w-full h-full flex-col items-center justify-start gap-10 p-8 
                    bg-gradient-to-t from-primary/80 via-[#E4FFE4] via-99% to-[#F5FAF5]
                    dark:bg-gradient-to-t dark:from-primary/80 dark:via-[#283328] via-99% dark:to-[#16151a]
                    "
                    >
                        <Header  />
                        {children}
                    </main>
                </ThemeProvider>
            </body>
        </html>
    );
}
